# Generated by Django 4.0.4 on 2022-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='This Item has no Description', max_length=300),
        ),
    ]
