# Generated by Django 4.0.4 on 2022-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.TextField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Leisure', 'Leisure'), ('Decor', 'Decor'), ('School', 'School'), ('Kitchen', 'Kitchen'), ('Technology', 'Technology')], default='General'),
        ),
    ]
