# Generated by Django 4.0.4 on 2022-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orders_alter_inventory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
