# Generated by Django 4.0.4 on 2022-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_orders_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
