# Generated by Django 4.0.4 on 2022-05-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_orders_item_price_inventory_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_price',
        ),
    ]
