# Generated by Django 4.0.4 on 2022-06-03 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Leisure', 'Leisure'), ('Decor', 'Decor'), ('School', 'School'), ('Kitchen', 'Kitchen'), ('Technology', 'Technology')], default='General', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_orders', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.moderator'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.moderator'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
