# Generated by Django 4.0.4 on 2022-06-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_category_remove_orders_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_owner',
        ),
    ]
