# Generated by Django 4.0.4 on 2022-06-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.customer'),
        ),
    ]
