# Generated by Django 4.0.4 on 2022-06-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_orders_order_returned_alter_orders_order_placed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number_of_orders',
        ),
    ]
